### PR TITLE
Flexible PIN length

### LINKED ISSUE #102: Flexible PIN length for CTAP 2.1
CTAP 2.1 can have longer PINs than 4 digits. Tests should adapt to not fail their setup.

### PR DESCRIPTION
**Pull request by kaczmarczyck**
Fixes #102.

The minimum PIN length is read in `GetInfo` and then used to generate a default PIN that works for the given minimum length. Anticipating more information from `GetInfo` to be useful for the `DeviceTracker` class, its `Initilization` now gets all information passed in.

### CODE REVIEW

File: src/command_state.h [hunk 1]
```diff
@@ -52,8 +52,9 @@ class CommandState {
   // if not already done. Safe to call multiple times, and only talks to the
   // authenticator if there is no PIN already. Defaults to 1234 if nothing else
   // is set. Fails if the PIN requirements are not satisfied.
-  Status SetPin(const cbor::Value::BinaryValue& new_pin_utf8 = {0x31, 0x32,
-                                                                0x33, 0x34});
+  Status SetPin(const cbor::Value::BinaryValue& new_pin_utf8);
+  // Sets the PIN as above, using a default.
+  Status SetPin();
```
Comment (ia0) [inline src/command_state.h:57]: The reason to not use optional parameters is to avoid having `DefaultPin` a (I think private should work) method of `CommandState`?

Same for `AttemptGetAuthToken`.

File: src/device_tracker.cc [hunk 2]
```diff
@@ -74,26 +74,34 @@ nlohmann::json TestResult::ToJson() const {
...
-                               const cbor::Value::ArrayValue& extensions,
-                               const cbor::Value::MapValue& options) {
+void DeviceTracker::Initialize(const cbor::Value::MapValue& info_map) {
   if (is_initialized_) {
     return;
   }
   is_initialized_ = true;
 
+  auto map_iter = info_map.find(CborValue(InfoMember::kVersions));
+  const cbor::Value::ArrayValue& versions = map_iter->second.GetArray();
```
Comment (ia0) [inline src/device_tracker.cc:84]: What if `map_iter == info_map.end()`? Should we assert that it's different?

**Review by ia0 — DISMISSED** [review]

File: src/command_state.h (hunk 1 above)
Comment (kaczmarczyck) [reply src/command_state.h:57]: The style guide says:
> Default arguments are allowed on non-virtual functions when the default is guaranteed to always have the same value.

Since the new default changes based on the length, I decided to overload instead. Also, would the optional parameter even work? I thought it only takes static values or functions?

File: src/device_tracker.cc (hunk 2 above)
Comment (kaczmarczyck) [reply src/device_tracker.cc:84]: The returned CBOR is checked in `fido_commands.cc`, including all map keys and values. There are several functions that take vetted CBOR maps and read their content, assuming it is checked. The alternatives are:
- runtime errors on failure (the current solution, as `GetArray` internally checks)
- explicitly checking everywhere
- parsing the maps into dedicated data structures (OpenSK style)

Switching to the third option would require a lot of extra work at this point. I don't see the additional benefit of adding asserts other than documenting assumptions?

File: src/command_state.h (hunk 1 above)
Comment (ia0) [reply src/command_state.h:59]: Oh right, if the min PIN length can change during runtime, it's an issue.

I don't know how much we can put in a default argument, I never use them.

File: src/device_tracker.cc (hunk 2 above)
Comment (ia0) [reply src/device_tracker.cc:84]: 1. I'm not sure that's a valid option. AFAICT `map_iter->second` should be undefined behavior if `map_iter == info_map.end()`.
2. Yes, this seems the less error-prone solution.
3. Yes, I also don't think it's worth it.
4. Have a precondition on the function that `info_map` contains an entry for "versions". Apparently that's the current option as I understand it. I'm fine with that if it's obvious that `info_map` should have a "versions" key. Otherwise I would document it in the header.

Comment (kaczmarczyck) [reply src/device_tracker.cc:84]: True, I forgot about the `->second`, my answer only takes the `.GetArray` into account. I'll add the precondition to the function documentation and assert-check the `end()`.

Comment (kaczmarczyck) [reply src/device_tracker.cc:86]: Done.

**Review by ia0 — APPROVED** [review]
